_target_: src.models.detct_graph_module.RlGraphModule
num_classes: 2
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.00035367122046193675
  # lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.con_graph_image_user_gat.RlGraph
  embedding_checkpoint_path: '.checkpoints/last.ckpt'
